### ISSUE TITLE
PA1/2/3 key causes runtime panic in ShowScreen()

### ISSUE THREAD

**Issue by moshix** [racingmars/go3270#2]
dbg: Got position bytes c5 e9, decoded to 361
dbg: Field 361: %
dbg: Got position bytes c6 f9, decoded to 441
dbg: Field 441: 
dbg: Got position bytes c8 c9, decoded to 521
dbg: Field 521: 
dbg: Got position bytes c9 d9, decoded to 601
dbg: Field 601: 
dbg: sending datastream: f5c311405b2902c0e842f4e5e3c1d440c1979740e285938583a389969511c27b2902c0e842f6e896a440a285938583a385847a404011c3f01de8d6e2404040404040e58599404040e2a8a2a3859440d5968485404011c5401d60a961e5d440404040f64bf4404040a9f1f1f4404040e2c5e5d4d4f111c5e82902c0c141f46c11c56a1d6011c6501d60a961e5d440404040f74bf1404040a9d7c4e3404040c8d6e4e5d4e9e5d411c6f82902c0c141f411c67a1d6011c7601d60e5d461c5e2c14040f24bf4404040c8859983404040c8d6e4e5d4c5e2c111c8c82902c0c141f411c84a1d6011c8f01d60a961e5d440404040f64bf4404040c8859983404040d4d6e2c8c9e7f411c9d82902c0c141f411c95a1d6011d2f02902c0e842f211d4401d60d79985a2a211d4c61de88595a3859911d44c1d60a39640a2a4829489a340a896a49940a28599a589838540838896898385115b601d60d7c6f340c5a789a311404013ffef
dbg: Got AID byte: 6e
panic: runtime error: index out of range [255] with length 255

goroutine 7 [running]:
github.com/racingmars/go3270.decodeBufAddr(...)
        /root/go3270/response.go:212
github.com/racingmars/go3270.readPosition(0x5523a0, 0xc000010048, 0x16e, 0x0, 0x0, 0x0, 0x0)
        /root/go3270/response.go:129 +0x28e
github.com/racingmars/go3270.readResponse(0x5523a0, 0xc000010048, 0xc000046c28, 0x2a9, 0x165, 0x0, 0x0, 0xc0000a9800, 0x2)
        /root/go3270/response.go:79 +0x75
github.com/racingmars/go3270.ShowScreen(0x5f9c20, 0x14, 0x14, 0xc000068810, 0x0, 0x0, 0x5523a0, 0xc000010048, 0x7d, 0x2b, ...)
        /root/go3270/screen.go:150 +0x3c6
main.handle(0x5523a0, 0xc000010048)
        /root/go3270/example/tn3270.go:149 +0x76b
created by main.main
        /root/go3270/example/tn3270.go:78 +0x155
exit status 2

Hopefully this can help in debugging. Good job with the colors!

thanks

**Comment by racingmars** [comment]
It looks like the PA keys are like the Clear key -- they just send the AID, they do not send the cursor position or field values. So they're more of an interrupt than a submission. I've updated the code to handle them just like Clear -- you get a Response back with nothing except the AID key set.
