### ISSUE TITLE
Connection forwarding capability

### ISSUE THREAD

**Issue by moshix** [racingmars/go3270#3]
Hello

One of 3-4 projects involving this very fun and interesting repo is to write a kind of VTAM connection multi-plexer, so that people who have several mainframes running in different places (like me), can log on to a go3270 program, and then chose whre to connect first. 

This would enable an important security feature so that emulated mainframe ports don't have to be all exposes to the Internet, only this go3270 program would have to be, and then it would forward 3270 connects to ports on the internal network. 

Pretty please?

great job @racingmars ! truly good out-of-the-box thinking!

M

**Comment by racingmars** [comment]
Stay tuned :-)

**Comment by racingmars** [comment]
At the moment, this doesn't appear to require any special 3270 capabilities; this can be accomplished with a generic approach to network proxying. I've created an application to do this, using this library for the initial host selection screen, at https://github.com/racingmars/proxy3270

Further development of the proxy3270 administrations screens, when the time comes, will be a good test case for the capabilities of this library!
