### ISSUE TITLE
Render Screen from JSON

### ISSUE THREAD

**Issue by WillianBR** [racingmars/go3270#7]
I was reading your library source code and thinking about a Manu Panel to manage servers without login in with SSH protocol.

Than I start to think if the screen could be stored as JSON Files with the screen description and a command line linked to the screen.

Let's say the screen has fields which are associate with the variable names (Nice touch by the way!).  So when the command was executed, we can use the field as variables name and pass to the command line.

We can even use go-lua (https://github.com/Shopify/go-lua.git) to handle the screen, after the data input and then execute a command.

Ofcouse! Using TLS to protect the connection stream and turn it safe!

What do you think about?  Do you wanna try? I can help with LUA. We can put it together and make some sample codes.

**Comment by racingmars** [comment]
This could certainly be a program you create that uses the library to provide its form capabilities, but I don't think this would require any modifications to the go3270 library itself.
